Fix lint warnings
jhipster/jhipster-kotlin pull request #257
Opened 2020-09-05 09:50 UTC by isaul32

2020-09-05 09:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/jhipster-kotlin?pullRequest=257) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/jhipster-kotlin?pullRequest=257) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/jhipster-kotlin?pullRequest=257) it.</sub>

2020-09-05 15:28 UTC, isaul32 commented
I think checks should fail if get any lint warning or error.

2020-09-07 18:52 UTC, sendilkumarn requested changes
Thanks @isaul32 for the PR.

2020-09-07 18:52 UTC, sendilkumarn commented on generators/server/templates/src/main/kotlin/package/security/SecurityUtils.kt.ejs
> +    }
nit: missing a tab here.

2020-09-09 22:19 UTC, sendilkumarn approved these changes
Awesome! Thanks. Thanks for fixing other indentation issues too.

2020-09-09 22:20 UTC, sendilkumarn commented
Congrats on your first contribution 🎉

2020-09-09 22:20 UTC, merged